// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCompiler.Data;

#nullable disable

namespace OnlineCompiler.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("OnlineCompiler.Models.CompilationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompilatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Errors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Poczet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CompilationResult");
                });

            modelBuilder.Entity("OnlineCompiler.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("FileModel");
                });

            modelBuilder.Entity("OnlineCompiler.Models.FileVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PublicFilesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicFilesId");

                    b.ToTable("FileVersion");
                });

            modelBuilder.Entity("OnlineCompiler.Models.ImportFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalPublicFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedFileId");

                    b.HasIndex("OriginalPublicFileId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ImportFile");
                });

            modelBuilder.Entity("OnlineCompiler.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedFileId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Librarie");
                });

            modelBuilder.Entity("OnlineCompiler.Models.LibraryAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("UserId");

                    b.ToTable("LibraryAccesse");
                });

            modelBuilder.Entity("OnlineCompiler.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPublic")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("OnlineCompiler.Models.ProjectLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLibrarie");
                });

            modelBuilder.Entity("OnlineCompiler.Models.PublicFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorOriginalFileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PublicFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorOriginalFileId")
                        .IsUnique();

                    b.ToTable("PublicFiles");
                });

            modelBuilder.Entity("OnlineCompiler.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OnlineCompiler.Models.UserFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.ToTable("UserFile");
                });

            modelBuilder.Entity("OnlineCompiler.Models.CompilationResult", b =>
                {
                    b.HasOne("OnlineCompiler.Models.Project", "Project")
                        .WithMany("CompilationResult")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OnlineCompiler.Models.FileModel", b =>
                {
                    b.HasOne("OnlineCompiler.Models.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OnlineCompiler.Models.FileVersion", b =>
                {
                    b.HasOne("OnlineCompiler.Models.PublicFiles", "PublicFiles")
                        .WithMany("Versions")
                        .HasForeignKey("PublicFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicFiles");
                });

            modelBuilder.Entity("OnlineCompiler.Models.ImportFile", b =>
                {
                    b.HasOne("OnlineCompiler.Models.FileModel", "ImportedFile")
                        .WithMany()
                        .HasForeignKey("ImportedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCompiler.Models.FileModel", "OriginalPublicFile")
                        .WithMany()
                        .HasForeignKey("OriginalPublicFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCompiler.Models.Project", "Project")
                        .WithMany("ImportedFile")
                        .HasForeignKey("ProjectId");

                    b.Navigation("ImportedFile");

                    b.Navigation("OriginalPublicFile");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OnlineCompiler.Models.Library", b =>
                {
                    b.HasOne("OnlineCompiler.Models.ImportFile", "ImportedFile")
                        .WithMany("ProjectLibraries")
                        .HasForeignKey("ImportedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCompiler.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedFile");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OnlineCompiler.Models.LibraryAccess", b =>
                {
                    b.HasOne("OnlineCompiler.Models.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCompiler.Models.User", "User")
                        .WithMany("AccessibleLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineCompiler.Models.Project", b =>
                {
                    b.HasOne("OnlineCompiler.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineCompiler.Models.ProjectLibrary", b =>
                {
                    b.HasOne("OnlineCompiler.Models.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCompiler.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OnlineCompiler.Models.PublicFiles", b =>
                {
                    b.HasOne("OnlineCompiler.Models.FileModel", "AuthorOriginalFile")
                        .WithOne("Share")
                        .HasForeignKey("OnlineCompiler.Models.PublicFiles", "AuthorOriginalFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorOriginalFile");
                });

            modelBuilder.Entity("OnlineCompiler.Models.UserFile", b =>
                {
                    b.HasOne("OnlineCompiler.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineCompiler.Models.FileModel", b =>
                {
                    b.Navigation("Share");
                });

            modelBuilder.Entity("OnlineCompiler.Models.ImportFile", b =>
                {
                    b.Navigation("ProjectLibraries");
                });

            modelBuilder.Entity("OnlineCompiler.Models.Project", b =>
                {
                    b.Navigation("CompilationResult");

                    b.Navigation("Files");

                    b.Navigation("ImportedFile");
                });

            modelBuilder.Entity("OnlineCompiler.Models.PublicFiles", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("OnlineCompiler.Models.User", b =>
                {
                    b.Navigation("AccessibleLibraries");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
